### ISSUE TITLE
Output fails with compilation error : PM Problem getting code lenses 

### ISSUE THREAD

**Issue by davidrehakcz** [gorkem/vscode-java#26]
I have successfully installed the extension:
1. folder ~/.vscode/extensions/redhat.java-0.0.3/server is present
2. The icon with "Thumbs up" is avalaible
3. Im using maven project structure
But whenever i perform any change, there is below stacktrace in output panel:

`[Error] Sep 19, 2016 3:59:20 PM Problem with codeSelect forNumberFormatValidator.java
t2si-api does not exist
Java Model Exception: Java Model Status [t2si-api does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)`

Im on linux, behind company proxy. Thanks in advance

**Comment by gorkem** [comment]
Is there an example project that we can use to reproduce?

**Comment by davidrehakcz** [comment]
It works at my home machine somehow. I'll review the installation at work once again. Closing this issue for now. Thanks
