### ISSUE TITLE
java.lang.NullPointerException v0.0.3

### ISSUE THREAD

**Issue by karelbecerra** [gorkem/vscode-java#34]
I just download the plugging (fresh Visual Studio) using Ubuntu 16.04

Visual Studio from (code_1.5.2-1473686317_amd64.deb)

[Error] Sep 22, 2016 10:19:08 AM Exception on incoming message dispatcher
null
java.lang.NullPointerException
at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.handleChanged(DocumentLifeCycleHandler.java:157)
at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.access$2(DocumentLifeCycleHandler.java:154)
at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler$1.run(DocumentLifeCycleHandler.java:98)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler.handle(DocumentLifeCycleHandler.java:95)
at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$ChangeHandler.handle(DocumentLifeCycleHandler.java:1)
at org.jboss.tools.langs.base.LSPServer.dispatchNotification(LSPServer.java:222)
at org.jboss.tools.langs.base.LSPServer.messageReceived(LSPServer.java:156)
at org.jboss.tools.langs.transport.AbstractConnection$DispatcherThread.run(AbstractConnection.java:32)

**Comment by tills13** [comment]
I've seen this issue when I try to run the extension on a project which doesn't have a pom.xml file in the root directory.

**Comment by fbricon** [comment]
Could you provide a sample project to reproduce the problem?

**Comment by karelbecerra** [comment]
Hello fbricon. I downloaded latest Visual Version (code_1.5.3-1474533365_amd64.deb) and install the plugin and its working.

Steps to reproduce:
1- sudo dpkg -i code_1.5.2-1473686317_amd64.deb
2- install the plugin
3- create a simple maven project (starter project)
4- edit a java file

**Comment by fbricon** [comment]
We need to ensure all usages of `JDTUtils.resolveCompilationUnit(uri)` are null-safe

**Comment by gorkem** [comment]
Fixed on LS repository
