### ISSUE TITLE
PM Creating working copy  empty does not exist

### ISSUE THREAD

**Issue by d2036a** [gorkem/vscode-java#39]
I am using vscode-java with selenium project.
After I cloned form https://github.com/SeleniumHQ/selenium.git,
I create 2 pom.xml files, one for /selenium/java/client, one for /selenium/java/server, as below.

`pom.xml` for client 
```xml
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.seleniumhq</groupId>
  <artifactId>client</artifactId>
  <version>2.52.0</version>
  <build>
    <directory>${project.basedir}/build</directory>
    <outputDirectory>${project.build.directory}/production</outputDirectory>
    <sourceDirectory>src</sourceDirectory>
    <testSourceDirectory>test</testSourceDirectory>
  </build>
</project>
```

`pom.xlm` for server
```xml
<project>
  <parent>
    <groupId>org.seleniumhq</groupId>
    <artifactId>client</artifactId>
    <version>2.52.0</version>
    <relativePath>../client/pom.xml</relativePath>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.seleniumhq</groupId>
  <artifactId>server</artifactId>
  <version>2.52.0</version>
  <build>
    <directory>${project.basedir}/build</directory>
    <outputDirectory>${project.build.directory}/production</outputDirectory>
    <sourceDirectory>src</sourceDirectory>
    <testSourceDirectory>test</testSourceDirectory>
  </build>
</project>
```

when I open a java file in the server project, everything works well,
but when I open a java file in the client project,
PM Problem encountered like below.
```
[Error] Sep 25, 2016 4:17:27 PM Creating working copy 
empty does not exist
Java Model Exception: Java Model Status [empty does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.Openable.getBuffer(Openable.java:285)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.handleOpen(DocumentLifeCycleHandler.java:142)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler.access$1(DocumentLifeCycleHandler.java:126)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$OpenHandler$1.run(DocumentLifeCycleHandler.java:75)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$OpenHandler.handle(DocumentLifeCycleHandler.java:72)
	at org.jboss.tools.vscode.java.handlers.DocumentLifeCycleHandler$OpenHandler.handle(DocumentLifeCycleHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchNotification(LSPServer.java:222)
	at org.jboss.tools.langs.base.LSPServer.messageReceived(LSPServer.java:156)
	at org.jboss.tools.langs.transport.AbstractConnection$DispatcherThread.run(AbstractConnection.java:32)

[Error] Sep 25, 2016 4:17:27 PM Problem getting code lenses forFirefoxDriver.java
empty does not exist
Java Model Exception: Java Model Status [empty does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1176)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.jboss.tools.vscode.java.handlers.CodeLensHandler.getCodeLensSymbols(CodeLensHandler.java:124)
	at org.jboss.tools.vscode.java.handlers.CodeLensHandler.access$0(CodeLensHandler.java:122)
	at org.jboss.tools.vscode.java.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:47)
	at org.jboss.tools.vscode.java.handlers.CodeLensHandler$CodeLensProvider.handle(CodeLensHandler.java:1)
	at org.jboss.tools.langs.base.LSPServer.dispatchRequest(LSPServer.java:210)
	at org.jboss.tools.langs.base.LSPServer.messageReceived(LSPServer.java:165)
	at org.jboss.tools.langs.transport.AbstractConnection$DispatcherThread.run(AbstractConnection.java:32)
```

**Comment by fbricon** [comment]
Did you open vscode before or after creating the pom.xml files?

**Comment by d2036a** [comment]
Yes, I opened vscode before and after creating the pom.xml file.
I create those 2 pom.xml by vscode, after editing, I closed vscode, and restarted it.

`.project` and `.classpath` were in the git repository, after open the vscode with java extension,
`.project` and `.classpath` have been changed.
